global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'escapade'
    static_configs:
      - targets: ['api:3001']
  
  # - job_name: 'system'
  #   static_configs:
  #     - targets: ['nodeexporter:9000']